### PR TITLE
Parallel queries enhancement. 

### PR DESCRIPTION
**Pull request by n-wbrown**
Addresses #37. 

This makes the queries to the Archiver execute in parallel as opposed to serially. 

Should be merged after #41. Most of the diff shown in this PR is caused by an early merge I made in order to handle some incompatibilities between the two branches.

### CODE REVIEW

**Comment by n-wbrown** [comment]
I believe this is now ready for merging.

**Comment by sasaki77** [comment]
I'm not sure the reason, but `top` and `bottom` functions doesn't work properly with this PR.
Could you check this?
aa-grafana

**Comment by n-wbrown** [comment]
@sasaki77 Thanks for letting me know. This issue should be fixed now.

My mistake was that in addition to parallelizing the queries, I had also parallelized the application of the functions. This caused problems as the top and bottom functions need knowledge of the other series in order to function and thus should not be applied to each request in an independent thread. I've moved the application of the functions back into the main process again and in local testing, the issue appears resolved.

**Comment by sasaki77** [comment]
thanks for fixing! Look OK.

**Pull request merged**
