### PR TITLE
Fix dataframe name from response to PV name

### LINKED ISSUE #59: Go Backend always returns a data frame with the name "response"
Data source plugin should return a data frame with the correct name, but Backend returns it with the name `response`.

https://github.com/sasaki77/archiverappliance-datasource/blob/74dc98d9c900799f61ac827434f09e642fe6fb1c/pkg/archiver-query.go#L472-L474

The Backend should return it with the PV name, as the value field in the data frame does.

### PR DESCRIPTION
**Pull request by sasaki77**
This PR fixes #59.

@n-wbrown Could you check the changes? I'll merge after you approve.

### CODE REVIEW

**Comment by klauer** [comment]
(@n-wbrown has recently moved on to other opportunities outside of SLAC. He might still respond to your request, but there's no guarantee.)

In any case - I think it's sensible to have the dataframe named appropriately with the PV name, and this _seems_ correct though I don't have a deep knowledge of the backend source.

**Comment by sasaki77** [comment]
Thank you for letting me know. I'll merge this PR.

I don't have enough knowledge of the Go backend, but I'll take care of it as far as I can.

**Comment by n-wbrown** [comment]
@sasaki77, My apologies for the slow response. While I've moved away from SLAC, I am still continuing light support for some projects. Unfortunately, I may not always be able to respond as quickly as I used to. The changes here look good.

@klauer Thanks for keeping an eye on this.

**Comment by sasaki77** [comment]
@n-wbrown I really appreciate all your work. I'll manage and fix Go backend too. If there are any problems, please let me know. Your supports are always welcome.

**Pull request merged**
